---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=djangoimager.conf.j2 dest=/etc/init/djangoimager.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=djangoimager state=restarted
